namespace KAMTestStand;

public class Entity
{
    public int CountDevicesVal { get; set; }
    public ResultE CountDevicesRes { get; set; }
    public int CurrDeviceVal { get; set; }
    public ResultE CurrDeviceRes { get; set; }
    public int DeviceIdVal { get; set; }
    public ResultE DeviceIdRes { get; set; }
    public int ExtPowerVal { get; set; }
    public ResultE ExtPowerRes { get; set; }
    public int ButtonShortVal { get; set; }
    public ResultE ButtonShortRes { get; set; }
    public int ButtonLongVal { get; set; }
    public ResultE ButtonLongRes { get; set; }
    public int ButtonDoubleVal { get; set; }
    public ResultE ButtonDoubleRes { get; set; }
    public int ButtonResetVal { get; set; }
    public ResultE ButtonResetRes { get; set; }
    public int Rs2321Val { get; set; }
    public ResultE Rs2321Res { get; set; }
    public int Rs2322Val { get; set; }
    public ResultE Rs2322Res { get; set; }
    public int Rs4851Val { get; set; }
    public ResultE Rs4851Res { get; set; }
    public int Rs4852Val { get; set; }
    public ResultE Rs4852Res { get; set; }
    public int Di1Val { get; set; }
    public ResultE Di1Res { get; set; }
    public int Di2Val { get; set; }
    public ResultE Di2Res { get; set; }
    public int DiCnt1Val { get; set; }
    public ResultE DiCnt1Res { get; set; }
    public int DiCnt2Val { get; set; }
    public ResultE DiCnt2Res { get; set; }
    public int KamVal { get; set; }
    public ResultE KamRes { get; set; }
    public int ModemStateVal { get; set; }
    public ResultE ModemStateRes { get; set; }
    public int Sim1Registered2GVal { get; set; }
    public ResultE Sim1Registered2GRes { get; set; }
    public int Sim1Registered3GVal { get; set; }
    public ResultE Sim1Registered3GRes { get; set; }
    public int Sim2Registered2GVal { get; set; }
    public ResultE Sim2Registered2GRes { get; set; }
    public int Sim2Registered3GVal { get; set; }
    public ResultE Sim2Registered3GRes { get; set; }
    public int Sim1IpAddr2GVal { get; set; }
    public ResultE Sim1IpAddr2GRes { get; set; }
    public int Sim1IpAddr3GVal { get; set; }
    public ResultE Sim1IpAddr3GRes { get; set; }
    public int Sim2IpAddr2GVal { get; set; }
    public ResultE Sim2IpAddr2GRes { get; set; }
    public int Sim2IpAddr3GVal { get; set; }
    public ResultE Sim2IpAddr3GRes { get; set; }
    public int Sim1Rssi2GVal { get; set; }
    public ResultE Sim1Rssi2GRes { get; set; }
    public int Sim1Rssi3GVal { get; set; }
    public ResultE Sim1Rssi3GRes { get; set; }
    public int Sim2Rssi2GVal { get; set; }
    public ResultE Sim2Rssi2GRes { get; set; }
    public int Sim2Rssi3GVal { get; set; }
    public ResultE Sim2Rssi3GRes { get; set; }
    public int Sim1CountData2GVal { get; set; }
    public ResultE Sim1CountData2GRes { get; set; }
    public int Sim1CountData3GVal { get; set; }
    public ResultE Sim1CountData3GRes { get; set; }
    public int Sim2CountData2GVal { get; set; }
    public ResultE Sim2CountData2GRes { get; set; }
    public int Sim2CountData3GVal { get; set; }
    public ResultE Sim2CountData3GRes { get; set; }
    public int ToSleepVal { get; set; }
    public ResultE ToSleepRes { get; set; }
    public int ToSleepWithGsmVal { get; set; }
    public ResultE ToSleepWithGsmRes { get; set; }
    public int TimeVal { get; set; }
    public ResultE TimeRes { get; set; }
    public int TimeSyncVal { get; set; }
    public ResultE TimeSyncRes { get; set; }
    public int CurrentDcMaVal { get; set; }
    public ResultE CurrentDcMaRes { get; set; }
    public int CurrentAcUaVal { get; set; }
    public ResultE CurrentAcUaRes { get; set; }
    public int CurrentSleepUaVal { get; set; }
    public ResultE CurrentSleepUaRes { get; set; }
    public int CurrentGsmMaVal { get; set; }
    public ResultE CurrentGsmMaRes { get; set; }
    public int CurrentGsmPeakMaVal{ get; set; }
    public ResultE CurrentGsmPeakMaRes { get; set; }
    public int CurrentGsmAndSleepMaVal { get; set; }
    public ResultE CurrentGsmAndSleepMaRes { get; set; }
    public int ReadyTimeVal { get; set; }
    public ResultE ReadyTimeRes { get; set; }
    public int SerialNumberVal { get; set; }
    public ResultE SerialNumberRes { get; set; }
    public int LedLestVal { get; set; }
    public ResultE LedLestRes { get; set; }
    public int RunTestsVal { get; set; }
    public ResultE RunTestsRes { get; set; }
    public int ResetVal { get; set; }
    public ResultE ResetRes { get; set; }
    public int IoCntVal { get; set; }
    public ResultE IoCntRes { get; set; }
}